name: Pull Request  | CI | DUSK

on: pull_request

jobs:
  ci_dusk:
    runs-on: ${{ matrix.os }}
    name: pull-request | ci | dusk

    strategy:
      fail-fast: true
      matrix:
        group: ['nova', 'application']
        os: [ ubuntu-latest ]
        php: [ 8.2 ]
        node: [ 16 ]

    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Zurich"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Setup php env
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, fileinfo, mysql, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Prepare the environment
        run: cp .env.ci .env

      # Frontend dependencies
      - name: Install assets
        run: cp vite.config.js.example vite.config.js

      # Composer License
      - name: Apply Nova license
        run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_LICENSE_KEY }}
      - name: Install Composer dependencies
        run: composer install -q --no-progress --prefer-dist --no-interaction --no-suggest --optimize-autoloader --no-scripts

      # Set token
      - name: Set NPM token
        run: npm config set "//npm.fontawesome.com/:_authToken" ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      # Frontend dependencies
      - name: Install dependencies & build assets
        run: npm install && npm run build

      # Prepare Backend
      - name: Create Database
        run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE laravel character set UTF8mb4 collate utf8mb4_bin;"

        # Artisan commands
      - name: Publish Laravel Nova Assets
        run: php artisan vendor:publish --tag=nova-assets --ansi --force
      - name: Publish Laravel Horizon Assets
        run: php artisan vendor:publish --tag=horizon-assets --force
      - name: Run Migration
        run: php artisan migrate:fresh

      # Frontend tests
      - name: Clear Cache & Config
        run: php artisan cache:clear && php artisan config:clear
      - name: Set Chrome Drive
        run: php artisan dusk:chrome-driver --detect
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &
      - name: Run Laravel Server
        run: php artisan serve --no-reload &
      - name: Run Dusk Tests
        run: php artisan dusk --pest --group=${{ matrix.group }} --stop-on-failure

      # Store Screenshots
      - name: Store Log Artifacts Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Screenshots
          path: ./tests/Browser/screenshots

      # Store Screenshots
      - name: Store Log Artifacts Console
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Console
          path: ./tests/Browser/console

      # Store .env
      - name: Store Environment
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Environment
          path: .env

      # Store vite.js
      - name: Store Vite
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Vite
          path: vite.config.js
